(load "cp1.ss")


; (define test-atom-symbol (evaluate 'ha env-init))
(define (helper e)
  (let ((res (evaluate e env-global)))
    (display res)
    (newline))
)
(helper "hah")
(helper "42")
(helper #\c)
(helper (vector #\c 42))
(helper '(quote (this is my quote)))
(helper '(quote this))
(helper '(if #t #f #t))
(helper '(begin "haha" #\c (if #f #t #f)))

(definitial a 1)
(definitial b 2)
(definitial c 3)
(helper 'a)
(helper 'b)
(helper 'c)
(helper '(set! a 42))
(helper '(lambda (a b) a))
(helper '((lambda (a) a) 42))
(helper '((lambda (a b) (list a b)) 42 32))
; test apply
(helper '(apply (lambda (a b) (list a b)) '(42 32)))