[package]
name = "r1"
version = "0.1.0"
authors = ["siriusdemon <mory2016@126.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }